project:
  type: website
  output-dir: docs

website:
  title: "continuum"
  site-url: https://serhatbe.github.io/continuum/
  description: "A blog"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."

format:
  html:
    toc: true
    theme: cosmo #journal
    css: styles.css
    code-copy: true
editor: visual

