project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  title: "continuum"
  site-url: https://serhatbe.github.io/continuum/
  description: "random notes and daily miscellany"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/
  back-to-top-navigation: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."

format:
  html:
    toc: true
    theme: cosmo #journal
    css: styles.css
    code-copy: true
date-format: full
editor: visual

