---
title: "Cheat Sheet"
date: "2023-January-01"
format:
  html:
    code-fold: true
    code-copy: true
categories:
  - 2023
  - Code
  - Quarto
  - Icons
---

## OS

-   pwd to see what the current working directory is.
-   ls to list directory contents.
-   cd foo to change to the foo sub-directory of your working directory.
-   cd .. to move up to the parent of the working directory.
-   mkdir foo to create a sub-directory called foo in the working directory.
-   up-arrow to go back through your command history.
-   tab to complete directories and file names.

## Pandoc

To convert md to HTML, use this command:

``` r
pandoc test1.md -f markdown -t html -s -o test1.html
```

To convert a whole directory of files from md to HTML in linux or OSX:

``` r
for f in *.md; do pandoc "$f" -s -o "${f%.md}.html"; done
```

HTML with table of contents, CSS, and custom footer:

``` r
pandoc -s --toc -c pandoc.css -A footer.html MANUAL.txt -o MANUAL.html
```

## Quarto

1.  Sample \_quarto.yml file:

``` r
project:
  type: website
  output-dir: docs
execute:
  freeze: true

website:
  title: "The Deep Keel"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Practice"
        href: blog.qmd
      #- about.qmd
      - playlist.qmd
      - equipment.qmd
      # - section: "Etc."
      #   contents:
      #     - playlist.qmd
      #     - equipment.qmd

  back-to-top-navigation: true
  page-footer: 
    left: "2013-2023, The Deep Keel"
    background: light
format:
  html:
    toc: true
    theme: cosmo #default journal cosmo litera 
    css: styles.css
date-format: full
editor: visual
```

2.  Sample \_quarto.yml file:

``` r
project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  title: "continuum"
  site-url: 
  description: "random notes and daily miscellany"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: 
  back-to-top-navigation: true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."

format:
  html:
    toc: true
    theme: cosmo #journal
    css: styles.css
    code-copy: true
date-format: full
editor: visual
```

3.  Sample \_quarto.yml file:

``` r
project:
  type: website
  output-dir: docs
execute:
  freeze: true

website:
  title: "Freewheelin' the Byways"
  navbar:
    right:
      - equipment.qmd
  back-to-top-navigation: true
  page-footer: 
    left: "2007-2023, Freewheeling the Byways"
    background: light
format:
  html:
    toc: true
    theme: sketchy #default journal cosmo litera sketchy
    css: styles.css
date-format: full

editor: visual
```

4.  Sample index.qmd file:

``` yaml
---
title: "Ride with the wind and due care!"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: cloud #numbered unnumbered cloud
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---
```

5.  To render all \*.qmd files in posts to generate HTML in docs, use this command in RStudio Terminal (do not use Build\>Render):

``` r
quarto render
```

6.  To use Font Awesome icons, run the following in your terminal in the Quarto project you want to use these icons.

``` r
quarto install extension quarto-ext/fontawesome
```

Input examples:

| Shortcode                                          | Icon                                    |
|----------------------------------------------------|-----------------------------------------|
| `{{{< fa thumbs-up >}}}`                           | {{< fa thumbs-up >}}                    |
| `{{{< fa folder >}}}`                              | {{< fa folder >}}                       |
| `{{{< fa chess-pawn >}}}`                          | {{< fa chess-pawn >}}                   |
| `{{{< fa book >}}}`                                | {{< fa book >}}                         |
| `{{{< fa brands bluetooth >}}}`                    | {{< fa brands bluetooth >}}             |
| `{{{< fa brands twitter size=2xl >}}}` (HTML only) | {{< fa brands twitter size=2xl >}}      |
| `{{{< fa brands github size=5x >}}}` (HTML only)   | {{< fa brands github size=5x >}}        |
| `{{{< fa battery-half size=Huge >}}}`              | {{< fa battery-half size=Huge >}}       |
| `{{{< fa envelope title="An envelope" >}}}`        | {{< fa envelope title="An envelope" >}} |

## Server

Start Python server:

``` python
python3 -m http.server
```

Go to the URL

``` python
localhost:8000
```
