---
title: "n Rules for Life"
date: "2023-May-16"
date-modified: "2023-June-23"
format: 
  html: default
  #pdf: default
categories:
  - 2023
  - Notes
  - Reflections
bibliography: references.json
---

1.  Accept things as they are whether agreeable or disagreeable. @suzuki2020

2.  Never lose sight of ultimate purpose, your physical and mental health: You're sane and breathing this minute and may be gone forever the next minute. (Unknown, probably Aurelius) Maintain your physical fitness and sanity.

3.  Practice any art, music, singing, dancing, acting, drawing, painting, sculpting, poetry, fiction, essays, reportage, no matter how well or badly, not to get money and fame, but to experience becoming, to find out what's inside you, to make your soul grow. -- Kurt Vonnegut

4.  No hurry, no pause: When you rush, time shrinks. When you're relaxed, time expands. This is true even though it's very hard for the mind to get. When you're relaxed and doing something willingly, you're participating in life. (Jon Schreiber, Breema Center)

5.  You are what you think: Keep an untroubled spirit; for all things must bow to Nature's Law @aurelius2003

6.  Reflect on what you've read and written: Information becomes knowledge by reflection. Reflection cultivates intuition. abundant intuition makes up for lack of information thereby enabling you operate where your knowledge is limited. (Unknown)

7.  Give your attention proportioned to the merits of the case: Sometimes full attention, sometimes none. (Unknown)

8.  Focus not so much on words but on actual behavior. (Don't watch his mouth, watch his hands. -- Adler's dictum).

9.  Do not try to stay on top of things (you cannot). Instead try to get to the bottom of things. (This kind of success, while not guaranteed, will be more fulfilling than the former).

10. It is more important to invest in good people than in good ideas. (bet on the jockey not the horse).

11. Work expands to fill the time available for its completion (Parkinson's law).

12. Perceive those things which cannot be seen (e.g. pay attention even to trifles). And do nothing which is of no use. (Miyamoto Musashi)

13. One who makes a show of valor is hated by others, even he achieves something, it is not praised but denied. (Kumazawa Banzan)

14. In the short term, you are as good as your intensity. In the long term, you are only as good as your consistency.

15. We read the same facts differently. For an optimist philosopher the universe spells victory, for a pessimist, defeat. (William James, from Pragmatism and Other Writings).

------------------------------------------------------------------------

::: callout-note
-   Revised on 2023-June-23
-   Revised on 2023-May-16
-   Revised on 2023-February-10
-   Revised on 2023-February-07
:::
