---
title: "Novelist as a Vocation"
date: "2023-June-6"
format: 
  html: default
  pdf: default
categories:
  - 2023
  - Notes
  - Haruki Murakami
  - Japan
  - Fiction
  - Life
bibliography: references.json
---

## New Book

Novelist as a Vocation by @murakami2022

## **Excerpt. © Reprinted by permission. All rights reserved**[^1]**.**

[^1]: [link](https://www.amazon.ca/Novelist-as-Vocation-Haruki-Murakami-ebook/dp/B09S3LBFHS/ref=sr_1_5?adgrpid=1350200510852514&hvadid=84388043562554&hvbmt=be&hvdev=c&hvlocphy=5076&hvnetw=s&hvqmt=e&hvtargid=kwd-84387701647169%3Aloc-32&hydadcr=14268_13443533&keywords=murakami&qid=1686093519&s=digital-text&sr=1-5)

Writing fiction is an entirely personal process that takes place in a closed room. Shut away in a study, you sit at a desk and (in most cases) create an imaginary story out of nothing and put it in the form of writing. The formless and subjective is transformed into something tangible and objec-tive (or at least something that seeks to be objective). Defined sim-ply, this is the day-to-day work we novelists perform.I'm sure there are many people who will say, "But wait, I don't have anything like a study." The same was true for me when I started out writing---I had nothing resembling a study to work in. In my tiny apartment near the Hatonomori Hachiman Shrine in Sendagaya (in a building that's since been torn down) I sat at the kitchen table late at night after my wife had gone to bed, scratching away with a pen on Japanese-style manuscript paper. That's how I wrote my first two novels, Hear the Wind Sing and Pinball, 1973. "Kitchen-table" fiction is what I've dubbed these early works.\
\
When I first started writing Norwegian Wood, I wrote at cafés in various places in Greece, on board ferry boats, in the wait-ing lobbies of airports, in shady spots in parks, and at desks in cheap hotels. Hauling around oversized, four-hundred-character- per-page Japanese manuscript paper was too much, so in Rome I bought a cheap notebook (the kind we used to call college-ruled notebooks) and wrote the novel down in tiny writing with a dis-posable Bic pen. I still had to contend with noisy cafés, wobbly tables that made writing difficult, coffee spilling on the pages, and at night in my hotel room when I'd go over what I'd written, some-times there would be couples getting all hot and heavy beyond the paper-thin walls separating my room from the room next door. Things weren't easy, in other words. I can smile at these memories now, but at the time it was all pretty discouraging. I had trouble finding a decent place to live, and moved all over Europe, all the while continuing to work on my novel. And I still have that thick old notebook, with its coffee stains (or whatever they are; I'm not really sure about some of them).\
\
Wherever a person is when he writes a novel, it's a closed room, a portable study. That's what I'm trying to say.
