---
title: "Right Practice: Posture & Breathing"
date: "2023-June-22"
format: 
  html: default
categories:
  - 2023
  - Notes
  - Shunryu Suzuki
  - Beginner's mind
  - Japan
  - Philosophy
  - Life
bibliography: references.json
---

## Right Practice

Zazen practice is the direct expression of our true nature. @suzuki2020

### Posture

It's not for obtaining the right state of mind, the posture itself is the right state of mind.

-   Keep your spine straight.

-   In posture, you're not one or not two. Body and mind is both.

-   Our body and mind shouldn't be wobbling or wandering, right posture will bring you a steady state. But it's not about right state of mind, the posture itself is the right state of mind.

-   Keep right posture in everything you do.

-   When. you try to attain something, your mind starts to wander about somewhere else. When you do not try to attain anything, you have your own body and mind right here.

-   When we have our body and mind in order, everything else will exist in the right place, in the right way.

-   Enlightenment is not some good feeling or some particular state of mind. The state of mind that exists when you sit in the right posture is, itself, enlightenment.

### Breathing

When we practice zazen our mind always follows or breathing, concentrate on your breathing, the fundamental activity of universal being.

## References
