---
title: "The Art of Practicing"
date: "2023-06-02"
format: 
  html: default
  pdf: default
categories:
  - 2023
  - Madeline Bruser
  - Non-fiction
  - Flow state
  - Philosophy
bibliography: references.json
---

## One Sentence Summary

The Art of Practicing by @bruser1999 contains wisdom and practical advise. Performance as a practice see page 216.

## A Ten-Step Approach

1.  Stretch
2.  Settle down in your environment: Be present, correct posture, breathing.
3.  Tune into your heart: Recalling profound feelings is how to tune into your heart.
4.  Use your body in a comfortable and natural way. Mechanics, habits and emotions...
5.  Follow your curiosity as you practice.
6.  Recognize three styles of struggle:
    1.  Overstated passion, in which we cling to the music.
    2.  Avoidance, in which we resist dealing with the music.
    3.  Aggression, in which we attack the music.
7.  Drop your attitudes and be simple.
8.  Apply three listening techniques:
    1.  Sing the notes and lines.
    2.  Place your attention on the vibrations.
    3.  Place your attention on each sound as it resonates in the space around you.
9.  Organize notes into groups, phrases, and textures.
10. Place your attention on the sensations of touch and movement.

## Key Takeaways

-   Relax, tension is your worst enemy
-   Hear the music you're playing
-   Be gentle to yourself
-   Do not over practice, short mindful work is superior to long laboured practice sessions.

## Miscellaneous Notes

-   Swing the music instead of sounding like sewing machine. Group notes and play them by creating a forward motion.
-   Focus on more on the sensations of touch and movement and use your vision mainly to check that what you feel is in accord with what you see. Bruser & Menuhin (1999, p. 200).
-   Think the sound you make. Then discover the sensation your brain has created for you. Bruser & Menuhin (1999, p. 201).
