---
title: "On Human Stupidity"
date: "2023-June-15"
date-modified: "2023-July-12"
categories:
  - 2023
  - Notes
  - Carlo M. Cipolla
  - Philosophy
  - Life
bibliography: references.json
---

## The Fourth Law of Stupidity

Non-stupid people always underestimate the damaging power of stupid people. In particular, they constantly forget that at all times and places and under any circumstances to deal and/or associate with stupid people infallibly turns out to be a costly mistake. @cipolla2019

Helpless people are through their own nature will fail to recognize how dangerous stupid people are. Intelligent people and bandits also are tempted to believe or associate themselves with a stupid individual. However this can have a disastrous effects:

1.  It is based on a complete misunderstanding of the essential nature of stupidity,
2.  It gives the stupid person added scope for the exercise of his gifts.

## Avoid Stupid People

Because of the erratic behavior of the stupid, one cannot foresee all the stupid's actions and reactions, and before long one will be pulverized by the unpredictable moves of the stupid partner.

## History

In public and private life, innumerable individuals have failed to understand the Fourth Law. The failure has caused incalculable losses in the history of mankind.

## References
