---
title: "The Basic Laws of Human Stupidity"
date: "2023-June-11"
format: 
  html: default
  #pdf: default
categories:
  - 2023
  - Notes
  - Carlo M. Cipolla
  - Philosophy
  - Life
bibliography: references.json
---

The basic laws assert that (@cipolla2021)

1.  Always and inevitably everyone underestimates the number of stupid individuals in circulation.

2.  The probability that a certain person be stupid is independent of any characteristic of that person.

3.  A stupid person is a person who causes losses to another person or to a group of persons while himself deriving no gain and even possibly incurring losses.

4.  Non-stupid people always underestimate the damaging power of stupid individuals. In particular non-stupid people constantly forget that at all times and places and under any circumstances to deal and/or associate with stupid people infallibly turns out to be a costly mistake.

5.  A stupid person is the most dangerous type of person. A stupid person is more dangerous than a bandit.

> Intelligence and stupidity are not the opposite of one another, nor is stupidity the lack of intelligence, but intelligence is the product, more or less unsuccessful, of a continuous series of attempts to dominate, or escape, the stupidity that constitutes everything that is human --- Matthijs Van Boxsel.

## Reference(s)
